### PR TITLE
add archipelago channel to ?sr command

### PR DESCRIPTION
**Pull request by adamdruppe**
I didn't actually test this but by eyeballing the code I'm pretty sure it should work...

### CODE REVIEW

**Comment by adamdruppe** [comment]
Oh I just realized the new channel would still go in races organization instead of in the app category.

Fairly small change again, I'll come back to it.

**Comment by adamdruppe** [comment]
so if instead of

```
category=get(ctx.guild.categories,
                                              name=constants.races_category),
```
It just did

```
category = ctx.channel.category
```

would that work? i guess it depends on if the channel object there actually has a category member. maybe i should try to make a test setup after all. But if it does have such a member that'd be a pretty useful behavior and then it doesn't need that other constant anymore.

**Comment by adamdruppe** [comment]
unless this doesn't really matter. since only the people who joined it the room anyway. just some scroll up and down might be annoying

**Comment by adamdruppe** [comment]
What about race results too? I think that's an argument to actually keep it in the administration category after all. Unless wanted to make a new results under AP too. But I kinda like doing the minimal amount of work because I'm lazy and because it makes sense to keep things there anyway.

**Comment by Steven-Biro** [comment]
realistically, the organization of this is something to discuss with the discord admins, it could be made to post results and create the channels anywhere we want

**Comment by Steven-Biro** [comment]
for a test setup, you'll want to generate a discord bot token, and I had used the following (powershell script) to run the bot:
```
param(
    [string] $Mode
)

if($Mode -eq "lint-fix") {
    python -m autopep8 --aggressive --aggressive --experimental --max-line-length 79 -i -r .\src
}
if ($Mode -ne 'no-lint') {
    $LinterPassed = python -m flake8 --show-source --statistics ./src/
    if ($LinterPassed) {
        Write-Output $LinterPassed
        exit
    }
}
docker container stop ffrbot -t 0
docker container rm ffrbot
docker container stop ffrbot-db -t 0
docker container rm ffrbot-db
docker build -t ffrbot:local-test -f .\Dockerfile .
docker run -d --network=redis-network --name ffrbot-db --mount source=ffrbotvol,target=/data -d redis --appendonly yes
docker run --name ffrbot --network=redis-network -e REDIS_HOST=ffrbot-db -it ffrbot:local-test
```

I think @tetron  had looked at setting up a docker-compose file to do the same

**Comment by adamdruppe** [comment]
chadbert took the useful bits out of this and did a better version that he actually tested! so gonna close as redundant now.

**Pull request closed without merging**
