### PR TITLE
short aliases for in-game done and forfeit commands

### PR DESCRIPTION
**Pull request by adamdruppe**
because many of us have tried these and are surprised to find it doesnt work.

Again untested but looks simple enough I think it will work.

### CODE REVIEW

**Review by Steven-Biro — APPROVED** [review]

**Comment by Steven-Biro** [comment]
I'll merge this in when races aren't going on, I really should get back to working on FFR stuff to finish my bot re-write from almost a year ago :/

**Comment by Steven-Biro** [comment]
my mistake in merging this, the alias conflicts with the async forfeit command. It would require a refactor to have both processed by the same command but do different things

reverting this for now

**Comment by adamdruppe** [comment]
Oh I didn't even realize it was a thing in async. Oh well...

**Comment by Steven-Biro** [comment]
Thanks for putting up the PR anyways!

**Pull request merged**
